package server

import (
	"encoding/gob"
	"github.com/28Pollux28/webcross3d/internal/api"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
	"log"
)

var sessionStore = session.New()

func init() {
	// This registers the custom map type for session encoding
	gob.Register(map[[3]int]bool{})
}

func Main() {
	app := fiber.New()

	// Create your handler
	h := &api.Handler{SessionStore: sessionStore}

	// Register routes generated by oapi-codegen
	api.RegisterHandlers(app, h)

	log.Println("Server running on http://localhost:3000")
	if err := app.Listen(":3000"); err != nil {
		log.Fatalf("failed to start server: %v", err)
	}
}
